### ISSUE TITLE
Deserializing a class with more than 10 properties ignores JsonProperty name

### ISSUE THREAD

**Issue by araghon007** [pupsette/CompactJson#2]
The keys in the mProps dictionary are the class property names, rather than the names you can set through the JsonProperty attribute, which means the code that gets called if the class has more than 10 properties ignores the set name:
https://github.com/pupsette/CompactJson/blob/c29694afcfb8144333b7f73e57325a20d03b0a0d/src/CompactJson/ObjectConverter.cs#L467-L489

I haven't looked properly into how the keys are set, so I can't give much advice beside just removing that condition, which I assume would lower the performance.

**Comment by pupsette** [comment]
Thanks for your feedback. Fixed by the most recent commit.
